# 🔢 One Hot Encoding — Complete Guide

**One Hot Encoding** converts categorical variables into a binary (0/1) matrix format.  
Each unique category becomes a new column, with `1` indicating the presence and `0` indicating absence.

---
### Why One Hot Encoding?
- ML models work with **numbers**, not text
- Unlike Label Encoding, OHE avoids imposing **ordinal relationships** between categories
- Best for **nominal** (unordered) categories like Color, City, Gender

---

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

print("✅ Libraries imported successfully!")


✅ Libraries imported successfully!


In [3]:
documents = ["people watch movie",
            "people watch cricket",
            "people like movie",
            "people watch movie"]

In [5]:
tokens = [sentence.lower().split() for sentence in documents]

In [14]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'watch', 'movie']]

In [23]:
all_words = [[word] for sentence in tokens for word in sentence]

In [32]:
all_words


[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['watch'],
 ['movie']]

In [41]:
encoder = OneHotEncoder(sparse_output=False)


In [50]:
encoder.fit(all_words)

OneHotEncoder(dtype=<class 'int'>, sparse_output=False)

In [51]:
print("Vocabulary",encoder.categories_[0])

Vocabulary ['cricket' 'like' 'movie' 'people' 'watch']


In [52]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'watch', 'movie']]

In [53]:
for sentence in tokens:
    print(sentence)

['people', 'watch', 'movie']
['people', 'watch', 'cricket']
['people', 'like', 'movie']
['people', 'watch', 'movie']


In [57]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)


Sentence: ['people', 'watch', 'movie']
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]

Sentence: ['people', 'watch', 'cricket']
[[0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]

Sentence: ['people', 'like', 'movie']
[[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]

Sentence: ['people', 'watch', 'movie']
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]


## 🗂️ Step 2 — Create Dummy Dataset

We'll use a **Customer Purchase Dataset** with the following categorical columns:
- `Gender` → Male / Female
- `City` → Mumbai / Delhi / Bangalore / Chennai
- `Product_Category` → Electronics / Clothing / Food / Sports
- `Membership` → Gold / Silver / Bronze

In [42]:
# ── Dummy Customer Dataset ──────────────────────────────────────────
data = {
    'CustomerID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Gender':     ['Male', 'Female', 'Female', 'Male', 'Male',
                   'Female', 'Male', 'Female', 'Male', 'Female'],
    'City':       ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Mumbai',
                   'Delhi', 'Bangalore', 'Chennai', 'Mumbai', 'Delhi'],
    'Product_Category': ['Electronics', 'Clothing', 'Food', 'Sports', 'Electronics',
                         'Food', 'Clothing', 'Sports', 'Food', 'Electronics'],
    'Membership': ['Gold', 'Silver', 'Bronze', 'Gold', 'Bronze',
                   'Silver', 'Gold', 'Bronze', 'Silver', 'Gold'],
    'Purchase_Amount': [15000, 3200, 850, 5400, 22000,
                        1100, 7800, 4300, 960, 18500]
}

df = pd.DataFrame(data)
print("📋 Original Dataset:")
print(df.to_string(index=False))
print(f"\nShape: {df.shape}")
print(f"\nData Types:\n{df.dtypes}")

📋 Original Dataset:
 CustomerID Gender      City Product_Category Membership  Purchase_Amount
        101   Male    Mumbai      Electronics       Gold            15000
        102 Female     Delhi         Clothing     Silver             3200
        103 Female Bangalore             Food     Bronze              850
        104   Male   Chennai           Sports       Gold             5400
        105   Male    Mumbai      Electronics     Bronze            22000
        106 Female     Delhi             Food     Silver             1100
        107   Male Bangalore         Clothing       Gold             7800
        108 Female   Chennai           Sports     Bronze             4300
        109   Male    Mumbai             Food     Silver              960
        110 Female     Delhi      Electronics       Gold            18500

Shape: (10, 6)

Data Types:
CustomerID          int64
Gender                str
City                  str
Product_Category      str
Membership            str
Purchas

## 🔍 Step 3 — Explore Unique Categories

In [43]:
categorical_cols = ['Gender', 'City', 'Product_Category', 'Membership']

print("📊 Unique values in each categorical column:")
print("-" * 45)
for col in categorical_cols:
    uniques = df[col].unique().tolist()
    print(f"  {col:20s} → {uniques}")

📊 Unique values in each categorical column:
---------------------------------------------
  Gender               → ['Male', 'Female']
  City                 → ['Mumbai', 'Delhi', 'Bangalore', 'Chennai']
  Product_Category     → ['Electronics', 'Clothing', 'Food', 'Sports']
  Membership           → ['Gold', 'Silver', 'Bronze']


---
## 🛠️ Method 1 — One Hot Encoding using `sklearn`

`OneHotEncoder` from `sklearn.preprocessing` is the most widely used approach in ML pipelines.

In [44]:
# ── sklearn OneHotEncoder ───────────────────────────────────────────
encoder = OneHotEncoder(sparse_output=False, dtype=int)

# Fit and transform the categorical columns
encoded_array = encoder.fit_transform(df[categorical_cols])

# Get the generated feature names
feature_names = encoder.get_feature_names_out(categorical_cols)

# Build a DataFrame from the encoded array
df_encoded_sklearn = pd.DataFrame(encoded_array, columns=feature_names)

print("✅ sklearn OneHotEncoder Output:")
print(f"   New columns created: {len(feature_names)}")
print(f"   Feature names: {list(feature_names)}\n")
print(df_encoded_sklearn.to_string(index=False))

✅ sklearn OneHotEncoder Output:
   New columns created: 13
   Feature names: ['Gender_Female', 'Gender_Male', 'City_Bangalore', 'City_Chennai', 'City_Delhi', 'City_Mumbai', 'Product_Category_Clothing', 'Product_Category_Electronics', 'Product_Category_Food', 'Product_Category_Sports', 'Membership_Bronze', 'Membership_Gold', 'Membership_Silver']

 Gender_Female  Gender_Male  City_Bangalore  City_Chennai  City_Delhi  City_Mumbai  Product_Category_Clothing  Product_Category_Electronics  Product_Category_Food  Product_Category_Sports  Membership_Bronze  Membership_Gold  Membership_Silver
             0            1               0             0           0            1                          0                             1                      0                        0                  0                1                  0
             1            0               0             0           1            0                          1                             0                      0    

In [45]:
# ── Combine with original numerical columns ─────────────────────────
df_final_sklearn = pd.concat(
    [df[['CustomerID', 'Purchase_Amount']].reset_index(drop=True),
     df_encoded_sklearn],
    axis=1
)

print("🔗 Final Encoded Dataset (sklearn):")
print(f"   Shape: {df_final_sklearn.shape}")
print(df_final_sklearn.to_string(index=False))

🔗 Final Encoded Dataset (sklearn):
   Shape: (10, 15)
 CustomerID  Purchase_Amount  Gender_Female  Gender_Male  City_Bangalore  City_Chennai  City_Delhi  City_Mumbai  Product_Category_Clothing  Product_Category_Electronics  Product_Category_Food  Product_Category_Sports  Membership_Bronze  Membership_Gold  Membership_Silver
        101            15000              0            1               0             0           0            1                          0                             1                      0                        0                  0                1                  0
        102             3200              1            0               0             0           1            0                          1                             0                      0                        0                  0                0                  1
        103              850              1            0               1             0           0            0                   

---
## 🐼 Method 2 — One Hot Encoding using `pandas.get_dummies()`

The simplest and most readable approach — great for quick EDA and small datasets.

In [46]:
# ── pandas get_dummies ──────────────────────────────────────────────
df_pandas_ohe = pd.get_dummies(
    df,
    columns=categorical_cols,
    dtype=int
)

print("✅ pandas get_dummies Output:")
print(f"   Shape: {df_pandas_ohe.shape}")
print(f"   Columns: {list(df_pandas_ohe.columns)}\n")
print(df_pandas_ohe.to_string(index=False))

✅ pandas get_dummies Output:
   Shape: (10, 15)
   Columns: ['CustomerID', 'Purchase_Amount', 'Gender_Female', 'Gender_Male', 'City_Bangalore', 'City_Chennai', 'City_Delhi', 'City_Mumbai', 'Product_Category_Clothing', 'Product_Category_Electronics', 'Product_Category_Food', 'Product_Category_Sports', 'Membership_Bronze', 'Membership_Gold', 'Membership_Silver']

 CustomerID  Purchase_Amount  Gender_Female  Gender_Male  City_Bangalore  City_Chennai  City_Delhi  City_Mumbai  Product_Category_Clothing  Product_Category_Electronics  Product_Category_Food  Product_Category_Sports  Membership_Bronze  Membership_Gold  Membership_Silver
        101            15000              0            1               0             0           0            1                          0                             1                      0                        0                  0                1                  0
        102             3200              1            0               0             0      

---
## ⚡ Method 3 — One Hot Encoding using `numpy` (Manual)

Understanding the inner workings — manually creating the binary matrix using NumPy.

In [47]:
# ── Manual OHE with NumPy ───────────────────────────────────────────
def manual_one_hot(series):
    """Manually apply One Hot Encoding to a pandas Series using NumPy."""
    categories = sorted(series.unique())
    ohe_matrix = np.zeros((len(series), len(categories)), dtype=int)
    cat_to_idx = {cat: idx for idx, cat in enumerate(categories)}
    for row_idx, value in enumerate(series):
        ohe_matrix[row_idx, cat_to_idx[value]] = 1
    col_names = [f"{series.name}_{cat}" for cat in categories]
    return pd.DataFrame(ohe_matrix, columns=col_names)

# Apply to each categorical column and concatenate
encoded_parts = [df[['CustomerID', 'Purchase_Amount']].reset_index(drop=True)]
for col in categorical_cols:
    encoded_parts.append(manual_one_hot(df[col]))

df_numpy_ohe = pd.concat(encoded_parts, axis=1)

print("✅ Manual NumPy OHE Output:")
print(f"   Shape: {df_numpy_ohe.shape}")
print(df_numpy_ohe.to_string(index=False))

✅ Manual NumPy OHE Output:
   Shape: (10, 15)
 CustomerID  Purchase_Amount  Gender_Female  Gender_Male  City_Bangalore  City_Chennai  City_Delhi  City_Mumbai  Product_Category_Clothing  Product_Category_Electronics  Product_Category_Food  Product_Category_Sports  Membership_Bronze  Membership_Gold  Membership_Silver
        101            15000              0            1               0             0           0            1                          0                             1                      0                        0                  0                1                  0
        102             3200              1            0               0             0           1            0                          1                             0                      0                        0                  0                0                  1
        103              850              1            0               1             0           0            0                          0

---
## 📊 Step 4 — Comparison Summary

In [48]:
print("=" * 55)
print("  📊  ONE HOT ENCODING — METHOD COMPARISON")
print("=" * 55)
print(f"  Original Dataset Shape       : {df.shape}")
print(f"  sklearn OneHotEncoder Shape  : {df_final_sklearn.shape}")
print(f"  pandas get_dummies Shape     : {df_pandas_ohe.shape}")
print(f"  Manual NumPy OHE Shape       : {df_numpy_ohe.shape}")
print("=" * 55)
print()

summary = {
    'Method':       ['sklearn OHE',    'pandas get_dummies', 'Manual NumPy'],
    'Best For':     ['ML Pipelines',   'EDA / Quick Use',   'Learning'],
    'Handles New':  ['Yes (transform)', 'No',               'No'],
    'Output Type':  ['Array / DF',      'DataFrame',         'DataFrame'],
    'Ease of Use':  ['Medium',          'Very Easy',         'Hard']
}
print(pd.DataFrame(summary).to_string(index=False))

  📊  ONE HOT ENCODING — METHOD COMPARISON
  Original Dataset Shape       : (10, 6)
  sklearn OneHotEncoder Shape  : (10, 15)
  pandas get_dummies Shape     : (10, 15)
  Manual NumPy OHE Shape       : (10, 15)

            Method        Best For     Handles New Output Type Ease of Use
       sklearn OHE    ML Pipelines Yes (transform)  Array / DF      Medium
pandas get_dummies EDA / Quick Use              No   DataFrame   Very Easy
      Manual NumPy        Learning              No   DataFrame        Hard


---
## 🧠 Key Takeaways

| Concept | Detail |
|---|---|
| **When to use OHE** | For **nominal** categories with no natural order |
| **Dummy Variable Trap** | Use `drop_first=True` in `get_dummies` to avoid multicollinearity |
| **High Cardinality** | OHE can create too many columns — consider Target Encoding instead |
| **sklearn advantage** | Can `transform()` new unseen data using the fitted encoder |

In [49]:
# ── BONUS: Drop First to Avoid Dummy Variable Trap ──────────────────
print("⚠️  Avoiding the Dummy Variable Trap (drop_first=True):\n")

df_no_trap = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

print(f"   Shape WITH  all dummies : {df_pandas_ohe.shape}")
print(f"   Shape WITHOUT 1st dummy : {df_no_trap.shape}")
print(f"\n   Columns after drop_first:")
print(f"   {list(df_no_trap.columns)}")

⚠️  Avoiding the Dummy Variable Trap (drop_first=True):

   Shape WITH  all dummies : (10, 15)
   Shape WITHOUT 1st dummy : (10, 11)

   Columns after drop_first:
   ['CustomerID', 'Purchase_Amount', 'Gender_Male', 'City_Chennai', 'City_Delhi', 'City_Mumbai', 'Product_Category_Electronics', 'Product_Category_Food', 'Product_Category_Sports', 'Membership_Gold', 'Membership_Silver']
